'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5448
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Bosch_Tech.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1280797435iconLarge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1280797435iconLarge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1280797435iconLarge1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1280797435iconLarge1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _400_F_33838687_o26xemUPy7Vu381Proed24hAhYQXJ3Ey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("400_F_33838687_o26xemUPy7Vu381Proed24hAhYQXJ3Ey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property abstract_design_pattern_sparkle_31000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abstract-design-pattern-sparkle-31000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property address1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("address1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property administrator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("administrator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property administrator1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("administrator1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bosch_pst_700pe_pendulum_jigsaw_600w_240v_9940_p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bosch-pst-700pe-pendulum-jigsaw-600w-240v-9940-p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boschhitecagm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boschhitecagm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eccjobfair1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eccjobfair1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eccjobfair11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eccjobfair11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property eccjobfair12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("eccjobfair12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ghf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ghf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ghf1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ghf1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ghf2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ghf2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ghf3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ghf3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ghf4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ghf4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ghf5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ghf5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property grey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hornbosch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hornbosch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__1_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (1)1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property images__1_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images (1)2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kidownload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kidownload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property kthememgr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kthememgr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Leopard_Login_Backgrounds_by_LoafNinja() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Leopard_Login_Backgrounds_by_LoafNinja", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stock_photo_exit_icon_59433298() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stock-photo-exit-icon-59433298", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property transaction_329363_1263526858() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("transaction-329363-1263526858", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property V3029037() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("V3029037", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
